site_name: Squad Limaozine 

repo_name: squad-limaozine-trainees-engNet
repo_url: https://github.com/JeffersonSenaa/squad-limaozine-trainees-engNet.git

theme: 
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: https://raw.githubusercontent.com/JeffersonSenaa/squad-limaozine-trainees-engNet/refs/heads/main/docs/img/moovit.png 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

# plugins:
#   - search
#   - git-revision-date-localized

extra_css:
  - stylesheets/extra.css
    
nav:
  - Início: index.md
  - Visão do Produto: 
      - Visão do Produto: visao-produto.md
      - Rich Picture: rich-picture.md
  - Requisitos: 
      - PBB - Product Backlog Building: product-backlog.md
      - Backlog: backlog.md 
  - Modelagem: 
      - User Story Map: user-story.md
  - Priorização:
      - Moscow: moscow.md
  - Rastreabilidade: rastreabilidade.md
    